[package]
name = "llust-dm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "^0.14.0"
pam = "^0.7.0"
pwd = "^1.3.1"
maildir = "^0.5.0"
fork = "^0.1.18"